config/routes.rb
BountyHunterNetwork::Application.routes.draw do

  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'bounty_updates', to: 'statuses#index', as: :bounty_updates
  root to: 'statuses#index'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end
  
  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BountyHunterNetwork</title>
  <meta name="description" content="Bounty Hunter Network">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    "application", "bootstrap.min", "statuses", "profiles" %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'touch-icon-iphone-114.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
  <%= favicon_link_tag 'touch-icon-ipad-144.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-9">
          <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "BountyHunterNetwork", root_path, class: "navbar-brand" %>
          </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
              <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                  <li id="activity-feed"><%= link_to "Activity Feed", activities_path %></li>
                <% else %>
                  <li><%= link_to "Bounty Updates", bounty_updates_path %></li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                  <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
                  <li><%= link_to 'Albums', albums_path(current_user) %></li>
                  <li><%= link_to 'Friends', user_friendships_path %></li>
          	      <li><%= link_to "Log Out", logout_path %></li>
          	    <% else %> 
          	      <li><%= link_to "Register", register_path %></li>
          	      <li><%= link_to "Log in", login_path %></li>
          	    <% end %>
              </ul>
            </nav>
        </div>
      </div>
    </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <%= render_breadcrumbs %>
      <% flash.each do |type, message| %>
        <div class="alert <%= flash_class type %>">
          <button class="close" data-dismiss="alert">&times</button>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <br>
      <footer class="footer">
        <br>
          <p><a href="http://www.charliemassry.com">&copy 2014 Charlie Massry</a></p>
          <%= javascript_include_tag "application", "jquery.min", "jquery_ujs", "js-routes", "bootstrap.min", "handlebars-v1.3.0", "statuses", "profiles", "user_friendships" %>
          <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-44853592-1', 'bountyhunternetwork.com');
            ga('send', 'pageview');
          </script>
          <script id="activities-template" type="text/x-handlebars-template">
            <a class="dropdown-toggle" href="#">Activity Feed ({{count}})</a>
            <ul class="dropdown-menu">
              {{#each activities}}
                {{activityLink}}
              {{/each}}
              <li class="divider"></li>
              <li><a href="{{activityFeedLink}}">Activity Feed</a></li>
            </ul>
          </script>
      </footer>
    </div>
  </div>
</div>

</body>
</html>